name: 🤖 Salesforce Auto-Documentation

on:
  push:
    branches: [ main, develop, master ]
    paths:
      # Solo ejecutar cuando hay cambios en archivos Salesforce
      - 'force-app/**'
      - 'src/**'
      - '**/*.cls'
      - '**/*.trigger'
      - '**/*.flow-meta.xml'
      - '**/lwc/**/*.html'
      - '**/lwc/**/*.js'
      - '**/lwc/**/*.css'
      - '**/*.object-meta.xml'
      - '**/*.permissionset-meta.xml'
      - '**/*.md-meta.xml'
      - 'scripts/**'
      - '.github/workflows/**'

  # Permitir ejecución manual
  workflow_dispatch:
    inputs:
      force_regenerate:
        description: 'Forzar regeneración completa de documentación'
        required: false
        default: 'false'
        type: boolean

# Permisos necesarios
permissions:
  contents: read
  actions: write

jobs:
  generate-documentation:
    name: 📝 Generar Documentación Técnica
    runs-on: ubuntu-latest
    
    # Solo ejecutar si no es commit de documentación automática
    if: "!contains(github.event.head_commit.message, '[skip-docs]')"
    
    steps:
      # 1. Checkout del repositorio
      - name: 📦 Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Setup Python
      - name: 🐍 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          #cache: 'pip'

      # 3. Instalar dependencias
      - name: 📚 Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pathlib

      # 4. Verificar variables de entorno
      - name: 🔍 Verify Environment Variables
        run: |
          echo "✅ Verificando configuración..."
          
          if [ -z "${{ secrets.ANTHROPIC_API_KEY }}" ]; then
            echo "❌ ANTHROPIC_API_KEY no configurado"
            exit 1
          fi
          
          if [ -z "${{ secrets.ATLASSIAN_EMAIL }}" ]; then
            echo "❌ ATLASSIAN_EMAIL no configurado"
            exit 1
          fi
          
          if [ -z "${{ secrets.ATLASSIAN_API_TOKEN }}" ]; then
            echo "❌ ATLASSIAN_API_TOKEN no configurado"
            exit 1
          fi
          
          if [ -z "${{ secrets.ATLASSIAN_BASE_URL }}" ]; then
            echo "❌ ATLASSIAN_BASE_URL no configurado"
            exit 1
          fi
          
          if [ -z "${{ secrets.CONFLUENCE_SPACE_KEY }}" ]; then
            echo "❌ CONFLUENCE_SPACE_KEY no configurado"
            exit 1
          fi
          
          echo "✅ Todas las variables de entorno están configuradas"
          
          # Log de contexto (sin exponer secrets)
          echo "📋 Contexto del workflow:"
          echo "  - Repository: ${{ github.repository }}"
          echo "  - Branch: ${{ github.ref_name }}"
          echo "  - Commit: ${{ github.sha }}"
          echo "  - Actor: ${{ github.actor }}"
          echo "  - Event: ${{ github.event_name }}"

      # 5. Detectar cambios relevantes
      - name: 🔍 Detect Salesforce Changes
        id: changes
        run: |
          # Obtener archivos cambiados
          if [ "${{ github.event_name }}" = "push" ]; then
            if [ "${{ github.event.before }}" != "0000000000000000000000000000000000000000" ]; then
              CHANGED_FILES=$(git diff --name-only ${{ github.event.before }}..${{ github.sha }} || echo "")
            else
              # Primer push al repositorio
              CHANGED_FILES=$(git ls-tree -r --name-only ${{ github.sha }} || echo "")
            fi
          else
            # Workflow manual - analizar todos los archivos
            CHANGED_FILES=$(find . -name "*.cls" -o -name "*.trigger" -o -name "*.flow-meta.xml" | head -20)
          fi
          
          echo "changed-files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
          # Verificar si hay archivos Salesforce relevantes
          SALESFORCE_CHANGES=$(echo "$CHANGED_FILES" | grep -E '\.(cls|trigger|flow-meta\.xml|html|js|css|object-meta\.xml|permissionset-meta\.xml|md-meta\.xml)$|force-app/|src/|lwc/' || true)
          
          echo "salesforce-changes<<EOF" >> $GITHUB_OUTPUT
          echo "$SALESFORCE_CHANGES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
          if [ -n "$SALESFORCE_CHANGES" ] || [ "${{ github.event.inputs.force_regenerate }}" == "true" ]; then
            echo "has-changes=true" >> $GITHUB_OUTPUT
            echo "✅ Cambios Salesforce detectados:"
            echo "$SALESFORCE_CHANGES" | head -10
          else
            echo "has-changes=false" >> $GITHUB_OUTPUT
            echo "ℹ️ No hay cambios en archivos Salesforce relevantes"
          fi

      # 6. Generar documentación
      - name: 🤖 Generate Documentation with Claude
        if: steps.changes.outputs.has-changes == 'true'
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          ATLASSIAN_EMAIL: ${{ secrets.ATLASSIAN_EMAIL }}
          ATLASSIAN_API_TOKEN: ${{ secrets.ATLASSIAN_API_TOKEN }}
          ATLASSIAN_BASE_URL: ${{ secrets.ATLASSIAN_BASE_URL }}
          CONFLUENCE_SPACE_KEY: ${{ secrets.CONFLUENCE_SPACE_KEY }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REF: ${{ github.ref }}
        run: |
          echo "🚀 Iniciando generación de documentación..."
          echo "📊 Información del proceso:"
          echo "  - Repositorio: $GITHUB_REPOSITORY"
          echo "  - Commit: $GITHUB_SHA"
          echo "  - Actor: $GITHUB_ACTOR"
          echo "  - Confluence Space: $CONFLUENCE_SPACE_KEY"
          
          # Ejecutar script de documentación
          python scripts/generate-documentation.py
          
          # Verificar resultado
          if [ $? -eq 0 ]; then
            echo "✅ Documentación generada exitosamente"
          else
            echo "❌ Error en la generación de documentación"
            exit 1
          fi

      # 7. Crear comentario en commit con resultados
      - name: 💬 Create Commit Comment
        if: always() && steps.changes.outputs.has-changes == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const success = process.env.GENERATION_SUCCESS === 'true';
            const spaceKey = process.env.CONFLUENCE_SPACE_KEY;
            const baseUrl = process.env.ATLASSIAN_BASE_URL;
            
            let commentBody = '';
            
            if ('${{ job.status }}' === 'success') {
              commentBody = `
            ✅ **Documentación automática generada exitosamente**
            
            📊 **Información del proceso:**
            - 🕐 Timestamp: ${new Date().toISOString()}
            - 🏢 Confluence: ${baseUrl}
            - 📂 Space: ${spaceKey}
            - 🤖 Generado con: Claude API
            
            🔍 **Archivos procesados:**
            \`\`\`
            ${{ steps.changes.outputs.salesforce-changes }}
            \`\`\`
            
            📚 **Resultado:**
            - ✅ Análisis de código Salesforce completado
            - ✅ Documentación técnica generada/actualizada
            - ✅ Publicación en Confluence exitosa
            
            🔗 **Ver documentación:** [Confluence Workspace](${baseUrl})
              `;
            } else {
              commentBody = `
            ❌ **Error en generación de documentación automática**
            
            📊 **Información del proceso:**
            - 🕐 Timestamp: ${new Date().toISOString()}
            - ❌ Estado: Error
            - 🔧 Ver logs del workflow para detalles
            
            🔧 **Troubleshooting:**
            - Verificar variables de entorno (ANTHROPIC_API_KEY, ATLASSIAN_*)
            - Revisar permisos de Confluence
            - Comprobar formato de archivos Salesforce
            - Consultar logs detallados en Actions
              `;
            }
            
            try {
              await github.rest.repos.createCommitComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                commit_sha: context.sha,
                body: commentBody
              });
            } catch (error) {
              console.log('Error creando comentario:', error);
            }
        env:
          CONFLUENCE_SPACE_KEY: ${{ secrets.CONFLUENCE_SPACE_KEY }}
          ATLASSIAN_BASE_URL: ${{ secrets.ATLASSIAN_BASE_URL }}

      # 8. Generar resumen del job
      - name: 📊 Job Summary
        if: always()
        run: |
          echo "## 📊 Salesforce Auto-Documentation Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 📋 Repository Information" >> $GITHUB_STEP_SUMMARY
          echo "- **Repository:** ${{ github.repository }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch:** ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Actor:** ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Event:** ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          echo "### 🔍 Change Detection" >> $GITHUB_STEP_SUMMARY
          echo "- **Has Salesforce Changes:** ${{ steps.changes.outputs.has-changes }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ "${{ steps.changes.outputs.has-changes }}" == "true" ]; then
            echo "### ✅ Actions Taken" >> $GITHUB_STEP_SUMMARY
            echo "- 🤖 Claude API analysis executed" >> $GITHUB_STEP_SUMMARY
            echo "- 📝 Documentation generated/updated" >> $GITHUB_STEP_SUMMARY
            echo "- 🏢 Published to Confluence space: ${{ secrets.CONFLUENCE_SPACE_KEY }}" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### 📁 Processed Files" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            echo "${{ steps.changes.outputs.salesforce-changes }}" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          else
            echo "### ℹ️ No Action Required" >> $GITHUB_STEP_SUMMARY
            echo "- No relevant Salesforce changes detected" >> $GITHUB_STEP_SUMMARY
            echo "- Documentation generation skipped" >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 💰 Cost Information" >> $GITHUB_STEP_SUMMARY
          echo "- **Claude API:** ~$0.50-2.00 per execution" >> $GITHUB_STEP_SUMMARY
          echo "- **GitHub Actions:** Free for public repos" >> $GITHUB_STEP_SUMMARY
          echo "- **Confluence API:** Included in Atlassian subscription" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 🔗 Useful Links" >> $GITHUB_STEP_SUMMARY
          echo "- [Confluence Workspace](${{ secrets.ATLASSIAN_BASE_URL }})" >> $GITHUB_STEP_SUMMARY
          echo "- [Claude API Console](https://console.anthropic.com/)" >> $GITHUB_STEP_SUMMARY
          echo "- [Repository](https://github.com/${{ github.repository }})" >> $GITHUB_STEP_SUMMARY

  # Job de notificación (opcional)
  notify-completion:
    name: 🔔 Notify Completion
    runs-on: ubuntu-latest
    needs: generate-documentation
    if: always() && needs.generate-documentation.result != 'skipped'
    
    steps:
      - name: 📧 Send Notification
        run: |
          echo "📧 Proceso de documentación completado"
          echo "📊 Estado: ${{ needs.generate-documentation.result }}"
          echo "🔗 Workflow: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          
          # Aquí puedes agregar notificaciones adicionales:
          # - Slack webhook
          # - Discord webhook  
          # - Email notification
          # - Microsoft Teams
          
          # Ejemplo Slack (descomenta y configura SLACK_WEBHOOK_URL secret):
          # curl -X POST -H 'Content-type: application/json' \
          #   --data "{\"text\":\"📝 Documentación Salesforce actualizada en ${{ github.repository }}\"}" \
          #   ${{ secrets.SLACK_WEBHOOK_URL }}